// One entry per control: the hover hint, the Ctrl+K finder, tours and "Show me" all read this list.
// A test fails when a control in the UI has no entry here, or an entry is not used in the UI.

export type ControlTab = "lcms" | "ftir" | "plate-reader" | "ai" | "app";

export interface ControlHint {
  id: string;
  tab: ControlTab;
  label: string;
  what: string;
  typical?: string;
  keywords?: string[];
  // A panel/section that must be opened before the control is visible (see useRevealPanel).
  panel?: string;
  helpTopic?: string;
}

export const TAB_ROUTES: Record<ControlTab, string | null> = {
  lcms: "/lcms",
  ftir: "/ftir",
  "plate-reader": "/plate-reader",
  ai: "/ai",
  app: null,
};

export const TAB_LABELS: Record<ControlTab, string> = {
  lcms: "LCMS",
  ftir: "FTIR",
  "plate-reader": "Plate Reader",
  ai: "AI Assistant",
  app: "Everywhere",
};

export const CONTROLS: ControlHint[] = [
  {
    id: "app.help",
    tab: "app",
    label: "Help",
    what: "Opens the guide for this tab: what each part does, how results are calculated, and troubleshooting.",
    keywords: ["manual", "guide", "documentation", "f1"],
  },
  {
    id: "app.findControl",
    tab: "app",
    label: "Find a control",
    what: "Search every button and setting by name or purpose; Enter jumps to it and highlights it.",
    typical: "Ctrl+K (⌘K on a Mac)",
    keywords: ["search", "command", "where", "locate"],
  },
  {
    id: "app.experimentTag",
    tab: "app",
    label: "Experiment tag",
    what: "Groups files that belong to one experiment; tagged plates are combined in the Experiment view and the SI package.",
    typical: "e.g. \"MIC run 12\"",
    keywords: ["group", "link", "si package", "label"],
  },
  {
    id: "app.exportFigure",
    tab: "app",
    label: "Export figure",
    what: "Saves the chart for a paper or slides: 1:1 as on screen, or at a journal width, as SVG (vector) or PNG at the chosen DPI.",
    typical: "SVG, single column 85 mm, 600 DPI for PNG",
    keywords: ["save", "image", "png", "svg", "publication", "download"],
  },

  // Plate Reader
  {
    id: "plate.open",
    tab: "plate-reader",
    label: "Open plate",
    what: "Loads a BioTek Gen5 export or any sheet/CSV with an 8×12 block labelled A–H and 1–12. You can also drop files on the page.",
    typical: ".xlsx from Gen5",
    keywords: ["upload", "import", "file", "gen5", "excel"],
    helpTopic: "files",
  },
  {
    id: "plate.view",
    tab: "plate-reader",
    label: "Plate map / Results / Experiment",
    what: "Plate map sets which wells are which; Results shows this plate's charts; Experiment combines plates with the same tag.",
    keywords: ["tabs", "switch", "view"],
    helpTopic: "overview",
  },
  {
    id: "plate.grid",
    tab: "plate-reader",
    label: "Plate wells",
    what: "Each well shows its OD. Click a well to exclude or include it; with a group picked below, drag across wells to assign them.",
    keywords: ["well", "exclude", "include", "contaminated", "paint", "drag", "od"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.paint",
    tab: "plate-reader",
    label: "Paint wells as",
    what: "Pick a compound, growth control, blank or unassigned, then drag across wells on the plate to give them that role.",
    keywords: ["assign", "brush", "role", "group", "drag"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.template",
    tab: "plate-reader",
    label: "Template",
    what: "Applies a saved layout (compounds, dilution, controls) to this plate. Templates are shared by the whole lab.",
    keywords: ["preset", "saved layout", "load"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.deleteTemplate",
    tab: "plate-reader",
    label: "Delete template",
    what: "Removes the selected template for everyone in the lab. Plates already using it keep their layout.",
    keywords: ["remove template"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.top",
    tab: "plate-reader",
    label: "Top concentration",
    what: "Concentration in the first dilution column; each next column is divided by the factor. Remembered for the next plate.",
    typical: "1024 µg/mL",
    keywords: ["highest", "start", "concentration", "dose"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.unit",
    tab: "plate-reader",
    label: "Unit",
    what: "Concentration unit shown on the plate, charts, tables and exports.",
    typical: "µg/mL",
    panel: "plate.tab.map",
  },
  {
    id: "plate.direction",
    tab: "plate-reader",
    label: "Direction",
    what: "Whether the dilution series runs across columns (compounds in rows) or down rows (compounds in columns).",
    typical: "Across columns",
    keywords: ["orientation", "rows", "columns"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.factor",
    tab: "plate-reader",
    label: "Dilution factor",
    what: "How much each step is diluted from the one before.",
    typical: "÷2 (two-fold dilution)",
    keywords: ["serial", "two-fold", "step"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.range",
    tab: "plate-reader",
    label: "Dilution columns",
    what: "First (top concentration) and last column of the dilution series.",
    typical: "1 to 11 (column 12 = growth control)",
    keywords: ["from", "to", "first", "last"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.compoundName",
    tab: "plate-reader",
    label: "Compound name",
    what: "Name used on charts, tables, exports and the Experiment view.",
    keywords: ["rename", "sample", "polymer"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.compoundRows",
    tab: "plate-reader",
    label: "Compound rows",
    what: "The replicate rows this compound fills, as a range or list. Press Apply to update the plate.",
    typical: "A–C",
    keywords: ["replicates", "lines", "where"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.compoundKind",
    tab: "plate-reader",
    label: "Kind",
    what: "Sample for the compounds you test; Reference for a known antibiotic such as gentamicin, marked as reference in charts.",
    typical: "Sample",
    keywords: ["reference", "control antibiotic", "gentamicin"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.removeCompound",
    tab: "plate-reader",
    label: "Remove compound",
    what: "Takes the compound out of the form; its wells become unassigned after Apply.",
    panel: "plate.tab.map",
  },
  {
    id: "plate.addCompound",
    tab: "plate-reader",
    label: "Add compound",
    what: "Adds a sample compound to the form; type its rows, then press Apply.",
    keywords: ["new compound", "sample"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.addReference",
    tab: "plate-reader",
    label: "Add reference",
    what: "Adds a reference antibiotic (named Gentamicin by default) to the form, for a control on the same plate.",
    keywords: ["gentamicin", "antibiotic", "positive control"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.growthControl",
    tab: "plate-reader",
    label: "Growth control column",
    what: "Wells with bacteria and no compound: 100% growth. Each compound uses the growth-control wells in its own rows.",
    typical: "12",
    keywords: ["gc", "positive", "untreated", "100%"],
    panel: "plate.tab.map",
    helpTopic: "calculation",
  },
  {
    id: "plate.blank",
    tab: "plate-reader",
    label: "Blank rows",
    what: "Medium-only wells; their mean OD is subtracted from every well. Leave empty when the plate has no blank.",
    typical: "G–H",
    keywords: ["background", "medium", "sterile", "subtract"],
    panel: "plate.tab.map",
    helpTopic: "calculation",
  },
  {
    id: "plate.apply",
    tab: "plate-reader",
    label: "Apply to plate",
    what: "Fills the plate from the form (compound rows, growth control, blank). Excluded wells stay excluded.",
    keywords: ["update", "fill", "layout"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.saveTemplate",
    tab: "plate-reader",
    label: "Save as template",
    what: "Saves this plate's layout (without excluded wells) under a name, for anyone in the lab to apply to other plates.",
    keywords: ["preset", "reuse", "store layout"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.subtractBlank",
    tab: "plate-reader",
    label: "Subtract blank",
    what: "Subtracts the mean OD of the blank wells from every well before averaging. Off: values are OD as read.",
    typical: "On when the plate has blank wells",
    keywords: ["background", "baseline", "medium"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.fit4pl",
    tab: "plate-reader",
    label: "4PL fit (IC₅₀)",
    what: "Fits a 4-parameter logistic curve to each compound's means and reports IC₅₀ ± SE, Hill slope and R².",
    typical: "Off; only meaningful when growth drops within the tested range",
    keywords: ["ic50", "sigmoid", "logistic", "curve", "hill"],
    panel: "plate.tab.results",
    helpTopic: "results",
  },
  {
    id: "plate.workbook",
    tab: "plate-reader",
    label: "Calculation workbook",
    what: "Excel file that redoes every step with live formulas from the raw plate, so you can check or change the numbers.",
    keywords: ["excel", "xlsx", "formulas", "audit", "reproduce"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.explain",
    tab: "plate-reader",
    label: "How is this calculated?",
    what: "Shows how this chart was calculated with this plate's wells and numbers, the automatic checks, and Excel steps to redo it.",
    keywords: ["explain", "method", "why", "checks", "trust"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.design",
    tab: "plate-reader",
    label: "Design",
    what: "Sets the chart title and axis labels used on screen and in exports.",
    keywords: ["title", "axis", "label", "style"],
    panel: "plate.tab.results",
  },
  {
    id: "plate.plateCsv",
    tab: "plate-reader",
    label: "Plate CSV",
    what: "Downloads the 8×12 plate as read (raw OD) as a CSV file.",
    keywords: ["raw", "download", "export"],
    panel: "plate.tab.results",
  },
  {
    id: "plate.resultsCsv",
    tab: "plate-reader",
    label: "Results CSV",
    what: "Downloads the results table: every replicate, n, mean, SD and % growth per compound and concentration.",
    keywords: ["table", "download", "export", "data"],
    panel: "plate.tab.results",
    helpTopic: "results",
  },
  {
    id: "plate.siPackage",
    tab: "plate-reader",
    label: "Download SI package",
    what: "Zip with methods text, tables and provenance for every plate with this experiment tag, for a paper's supporting information.",
    keywords: ["supporting information", "zip", "paper", "methods"],
    panel: "plate.tab.experiment",
    helpTopic: "experiment",
  },
  {
    id: "plate.exportAll",
    tab: "plate-reader",
    label: "Export all (Excel)",
    what: "One workbook with the MIC reading grid plus every plate's calculation sheets with live formulas.",
    keywords: ["excel", "xlsx", "workbook", "experiment"],
    panel: "plate.tab.experiment",
    helpTopic: "experiment",
  },
  // FTIR
  { id: "ftir.open", tab: "ftir", label: "Open FTIR files", what: "Loads one or more spectra (CSV, TXT/TSV, JCAMP-DX, SPC). You can also drop files on the page.", typical: ".csv or .jdx", keywords: ["upload", "import", "spectrum"], helpTopic: "files-workspace" },
  { id: "ftir.loadWorkspace", tab: "ftir", label: "Load workspace", what: "Restores spectra and settings from a workspace JSON file saved earlier.", keywords: ["restore", "json", "session"], helpTopic: "files-workspace" },
  { id: "ftir.saveWorkspace", tab: "ftir", label: "Save workspace", what: "Saves the open spectra and all settings to a JSON file you can load later or send to someone.", keywords: ["json", "store", "session"], helpTopic: "files-workspace" },
  { id: "ftir.exportPeaks", tab: "ftir", label: "Export peaks CSV", what: "Downloads the picked peaks with wavenumber, height, prominence and assignments.", keywords: ["table", "download", "csv"], helpTopic: "peaks-table" },
  { id: "ftir.exportJdx", tab: "ftir", label: "Export JDX", what: "Saves the processed spectrum as JCAMP-DX, readable by most spectroscopy software.", keywords: ["jcamp", "download", "spectrum file"] },
  { id: "ftir.report", tab: "ftir", label: "Report HTML", what: "Downloads a printable HTML page with the preprocessing settings and the peak/assignment table (no chart image).", keywords: ["print", "summary", "pdf"] },
  { id: "ftir.inspector", tab: "ftir", label: "Analysis sections", what: "Switches the right panel between Preprocess, Peaks & library, Deconvolution and Multi-overlay.", keywords: ["panel", "tabs", "sections"] },
  { id: "ftir.undoRedo", tab: "ftir", label: "Undo / redo", what: "Steps back or forward through changes to the settings in this section.", typical: "Ctrl+Z / Ctrl+Y", keywords: ["revert", "back"] },

  { id: "ftir.preset", tab: "ftir", label: "Preprocessing preset", what: "Fills smoothing, baseline and normalisation with settings suited to the sample type.", typical: "KBr disc, ATR sample, Polymer thin film, Raw film", keywords: ["sample type", "defaults", "kbr", "atr", "film"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.mode", tab: "ftir", label: "Mode", what: "Whether the file is absorbance or transmittance. Transmittance is converted to absorbance (A = −log₁₀T) before any other step.", typical: "Detected from the file", keywords: ["absorbance", "transmittance", "%t"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.smoothing", tab: "ftir", label: "Smoothing window", what: "Savitzky–Golay smoothing over this many points; 0 = off. Larger windows remove noise but broaden sharp bands.", typical: "0 (off) or 5", keywords: ["savgol", "noise", "smooth"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.polyOrder", tab: "ftir", label: "SavGol poly order", what: "Polynomial order of the smoothing; higher keeps peak shapes better but smooths less.", typical: "2", keywords: ["savitzky", "polynomial"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.baseline", tab: "ftir", label: "Baseline", what: "How the sloping background is removed: airPLS / AsLS (automatic, flexible), rubberband (convex hull), polyfit, or none.", typical: "airPLS", keywords: ["background", "correction", "airpls", "asls", "rubberband"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.normalize", tab: "ftir", label: "Normalize", what: "Scales each spectrum so samples can be compared: max (tallest peak = 1), area, vector, SNV, min-max, or none.", typical: "none for one sample; SNV or vector to compare", keywords: ["scale", "snv", "vector", "compare"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.baselineLambda", tab: "ftir", label: "Baseline lambda", what: "How stiff the AsLS/airPLS baseline is. Higher = smoother baseline that ignores broad bands; too low cuts into peaks.", typical: "1e5 (range 1e4–1e7)", keywords: ["stiffness", "smoothness", "airpls", "asls"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.asymmetry", tab: "ftir", label: "Asymmetry p", what: "AsLS only: how strongly the baseline stays under the peaks. Smaller = hugs the bottom more.", typical: "0.01 (range 0.001–0.1)", keywords: ["asls", "p"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.maskCo2", tab: "ftir", label: "Mask CO₂", what: "Excludes the CO₂ doublet (2310–2390 cm⁻¹) from peak picking and shades it. Water-vapour lines can't be masked; use background subtraction.", typical: "On if the CO₂ band shows", keywords: ["atmospheric", "co2", "carbon dioxide"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.atr", tab: "ftir", label: "ATR correction", what: "Approximate ATR correction: scales intensity by ν/ν_ref, since penetration depth grows at low wavenumber. Not a full optical correction.", typical: "On for ATR measurements", keywords: ["attenuated total reflectance", "penetration"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.atrN", tab: "ftir", label: "ATR crystal index", what: "Refractive index of the ATR crystal, used by the ATR correction.", typical: "1.5; diamond/ZnSe 2.4, Ge 4.0", keywords: ["refractive", "diamond", "germanium", "znse"], panel: "ftir.inspector.preprocess" },

  { id: "ftir.pickPeaks", tab: "ftir", label: "Pick peaks", what: "Finds peaks with the settings below and, when Assign bonds is on, labels them from the bond library.", typical: "Shortcut P", keywords: ["detect", "find peaks", "run"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.pickOverlay", tab: "ftir", label: "Pick on overlaid spectra", what: "Also picks peaks on every spectrum shown in the overlay (needs 2 or more overlaid).", keywords: ["all spectra", "batch"], panel: "ftir.inspector.peaks" },
  { id: "ftir.minProminence", tab: "ftir", label: "Min prominence", what: "How far a peak must stand out from its surroundings. Raise it if you get too many small peaks.", typical: "0.01", keywords: ["threshold", "noise", "sensitivity"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.minHeight", tab: "ftir", label: "Min height", what: "Optional absolute cut-off: peaks below this y-value (after preprocessing) are ignored. Empty = off.", typical: "off", keywords: ["threshold", "cutoff"], panel: "ftir.inspector.peaks" },
  { id: "ftir.minDistance", tab: "ftir", label: "Min distance", what: "Minimum spacing between two picked peaks, so one band isn't picked twice.", typical: "8 cm⁻¹", keywords: ["spacing", "separation", "duplicate"], panel: "ftir.inspector.peaks" },
  { id: "ftir.topN", tab: "ftir", label: "Top N peaks", what: "Keeps only the N most prominent peaks; 0 keeps all.", typical: "15", keywords: ["limit", "number of peaks", "max"], panel: "ftir.inspector.peaks" },
  { id: "ftir.assign", tab: "ftir", label: "Assign bonds", what: "Labels each peak with likely functional groups from the bundled bond library (v3).", typical: "On", keywords: ["library", "functional group", "label", "identify"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.shoulder", tab: "ftir", label: "Shoulder mode", what: "Uses second-derivative minima to also find shoulders and overlapping bands that are not separate maxima.", typical: "Off; on for crowded regions such as amide I", keywords: ["2nd derivative", "overlapping", "hidden"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.assignTopN", tab: "ftir", label: "Assign top N", what: "How many candidate assignments are kept per peak (shown in the label menu of the peak table).", typical: "3", keywords: ["candidates", "alternatives"], panel: "ftir.inspector.peaks" },
  { id: "ftir.assignMinScore", tab: "ftir", label: "Assign min score", what: "Candidates scoring below this (0–100) are hidden; if none pass, the best one is shown as low confidence.", typical: "35", keywords: ["confidence", "threshold", "score"], panel: "ftir.inspector.peaks" },
  { id: "ftir.relabel", tab: "ftir", label: "Apply & re-label", what: "Re-runs peak picking and library assignment with the exclusions below.", keywords: ["reassign", "update labels"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.excludeCategories", tab: "ftir", label: "Exclude categories", what: "Rule out functional-group families you know are absent (e.g. amide in a polyester), so they're never suggested.", keywords: ["rule out", "constraints", "functional group"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.excludeSubcategories", tab: "ftir", label: "Exclude subcategories", what: "Rule out finer groups (e.g. primary amide) while keeping the rest of their family.", keywords: ["rule out", "constraints"], panel: "ftir.inspector.peaks" },
  { id: "ftir.ambiguity", tab: "ftir", label: "Ambiguity ratio", what: "A label is set automatically only if the best candidate scores at least this many times the runner-up; otherwise it's marked ambiguous.", typical: "1.3", keywords: ["confidence", "ambiguous", "runner-up"], panel: "ftir.inspector.peaks" },

  { id: "ftir.integrateRegion", tab: "ftir", label: "Integration region", what: "Wavenumber range of the band to integrate (low and high limit).", typical: "1700–1750 cm⁻¹ (carbonyl)", keywords: ["band", "limits", "area"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.integrateBaseline", tab: "ftir", label: "Integration baseline", what: "Line under the band: linear (between the region ends), horizontal (at the lower end), or tangent (between the lowest points near each end).", typical: "linear", keywords: ["area", "background"], panel: "ftir.inspector.quant" },
  { id: "ftir.integrate", tab: "ftir", label: "Integrate", what: "Measures the band's area, height, FWHM and peak position in the chosen region.", keywords: ["area", "quantify", "band"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.subtractSession", tab: "ftir", label: "Subtract session", what: "The spectrum to subtract from the current one (e.g. a solvent, substrate or unreacted starting material).", keywords: ["difference", "reference", "background"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractK", tab: "ftir", label: "Scale k", what: "Difference = current − k × other. Adjust k until the shared bands cancel.", typical: "1", keywords: ["factor", "difference"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractAutoFit", tab: "ftir", label: "Auto-fit region", what: "Finds k automatically by best cancelling the two spectra in the fit region below.", keywords: ["automatic k", "least squares"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractRegion", tab: "ftir", label: "Subtraction fit region", what: "Wavenumber range used to fit k, ideally where only the subtracted component absorbs.", typical: "1000–1800 cm⁻¹", panel: "ftir.inspector.quant" },
  { id: "ftir.subtract", tab: "ftir", label: "Subtract", what: "Shows the difference spectrum (current − k × other) on the chart.", keywords: ["difference spectrum"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearDifference", tab: "ftir", label: "Clear difference", what: "Removes the difference spectrum from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.matchRegion", tab: "ftir", label: "Match region", what: "Wavenumber range compared against the built-in reference spectra.", typical: "650–1800 cm⁻¹", keywords: ["fingerprint"], panel: "ftir.inspector.quant" },
  { id: "ftir.matchDerivative", tab: "ftir", label: "Match derivative", what: "Compares spectra as-is (0) or as 1st/2nd derivatives, which ignore baseline differences and sharpen bands.", typical: "1st", keywords: ["correlation", "derivative"], panel: "ftir.inspector.quant" },
  { id: "ftir.matchTopN", tab: "ftir", label: "Match top N", what: "How many best-matching references to list.", typical: "8", panel: "ftir.inspector.quant" },
  { id: "ftir.match", tab: "ftir", label: "Match references", what: "Ranks the built-in reference spectra by Pearson correlation with this spectrum; click a hit to overlay it.", keywords: ["identify", "library", "compare", "polymer"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearReference", tab: "ftir", label: "Clear reference", what: "Removes the overlaid reference spectrum from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.fitPresets", tab: "ftir", label: "Fit presets", what: "Sets region, number of components and profile for common bands: amide I, carbonyl, O–H/N–H.", keywords: ["amide", "carbonyl", "secondary structure"], panel: "ftir.inspector.quant" },
  { id: "ftir.fitRegion", tab: "ftir", label: "Fit region", what: "Wavenumber range to deconvolute into sub-bands.", typical: "1600–1700 cm⁻¹ (amide I)", panel: "ftir.inspector.quant" },
  { id: "ftir.fitComponents", tab: "ftir", label: "Components", what: "Number of sub-bands to fit; start positions come from second-derivative minima. Too many gives unstable fits.", typical: "2–4", keywords: ["sub-bands", "peaks"], panel: "ftir.inspector.quant" },
  { id: "ftir.fitProfile", tab: "ftir", label: "Profile", what: "Band shape for each component: Gaussian, Lorentzian or a 50/50 Voigt mix.", typical: "Gaussian", keywords: ["shape", "voigt", "lorentz"], panel: "ftir.inspector.quant" },
  { id: "ftir.deconvolute", tab: "ftir", label: "Deconvolute", what: "Fits the components and reports each centre, FWHM, area and area %, with R² of the fit.", keywords: ["fit", "secondary structure", "sub-band"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearFit", tab: "ftir", label: "Clear fit", what: "Removes the fitted components from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.fitCsv", tab: "ftir", label: "Fit components CSV", what: "Downloads the fitted components: centre, assignment, FWHM, amplitude, area and area %.", keywords: ["download", "export fit"], panel: "ftir.inspector.quant" },

  { id: "ftir.overlayShow", tab: "ftir", label: "Show selected spectra", what: "Draws the spectra ticked below on the same chart.", typical: "Shortcut O", keywords: ["compare", "overlay", "multiple"], panel: "ftir.inspector.overlay", helpTopic: "overlay" },
  { id: "ftir.overlayMode", tab: "ftir", label: "Overlay mode", what: "overlay = on top of each other; offset = shifted up a little each; stacked = separate bands of the chart.", typical: "overlay", keywords: ["stack", "offset"], panel: "ftir.inspector.overlay" },
  { id: "ftir.overlaySelect", tab: "ftir", label: "Spectra to overlay", what: "Tick the open spectra to draw together with the current one.", panel: "ftir.inspector.overlay" },

  { id: "ftir.secondDerivative", tab: "ftir", label: "2nd derivative", what: "Overlays the inverted 2nd derivative (−d²A/dν²) to reveal hidden sub-bands and shoulders.", keywords: ["shoulders", "hidden bands"], helpTopic: "spectrum-chart" },
  { id: "ftir.showBaseline", tab: "ftir", label: "Show baseline", what: "Draws the fitted baseline that is subtracted, so you can check it follows the background and not the peaks.", keywords: ["background", "check baseline"], helpTopic: "spectrum-chart" },
  { id: "ftir.region", tab: "ftir", label: "Wavenumber region", what: "Zooms the chart to a preset range or your own limits.", typical: "Full 400–4000 cm⁻¹; Amide I & II 1500–1750", keywords: ["zoom", "range", "fingerprint", "axis"], helpTopic: "spectrum-chart" },
  { id: "ftir.design", tab: "ftir", label: "Design", what: "Opens chart display settings: line width, frame, grid, peak labels, font sizes and trace colours.", keywords: ["style", "appearance", "graph settings"], helpTopic: "spectrum-chart" },
  { id: "ftir.lineWidth", tab: "ftir", label: "Line width", what: "Thickness of the spectrum lines, on screen and in exports.", typical: "1.4", panel: "ftir.chart.design" },
  { id: "ftir.frame", tab: "ftir", label: "Frame", what: "Axis box around the plot: none, half (left and bottom axes) or full.", typical: "Half frame", panel: "ftir.chart.design" },
  { id: "ftir.ticks", tab: "ftir", label: "Show ticks", what: "Shows tick marks on the axes.", typical: "On", panel: "ftir.chart.design" },
  { id: "ftir.grid", tab: "ftir", label: "Show grid", what: "Shows grid lines behind the spectrum.", typical: "On", panel: "ftir.chart.design" },
  { id: "ftir.groupRegions", tab: "ftir", label: "Group regions", what: "Shades the typical wavenumber ranges of common functional groups behind the spectrum.", typical: "Off · shortcut F", keywords: ["functional groups", "bands", "shading"], panel: "ftir.chart.design" },
  { id: "ftir.labelColor", tab: "ftir", label: "Peak label colour", what: "Colour of the peak labels on the chart.", panel: "ftir.chart.design" },
  { id: "ftir.labelSize", tab: "ftir", label: "Peak label size", what: "Font size of the peak labels.", typical: "10", panel: "ftir.chart.design" },
  { id: "ftir.axisTitleSize", tab: "ftir", label: "Axis title size", what: "Font size of the axis titles.", typical: "13", panel: "ftir.chart.design" },
  { id: "ftir.axisTickSize", tab: "ftir", label: "Axis tick size", what: "Font size of the axis numbers.", typical: "12", panel: "ftir.chart.design" },
  { id: "ftir.traceColors", tab: "ftir", label: "Trace colours", what: "Colour of each spectrum on the chart and in exports.", keywords: ["colour", "color", "line colour"], panel: "ftir.chart.design" },
  { id: "ftir.peakTool", tab: "ftir", label: "Peak tool", what: "Inspect shows values on hover; Add places a peak where you click; Delete removes the peak you click.", keywords: ["manual peak", "add peak", "remove peak", "click"], helpTopic: "peak-pick" },
  { id: "ftir.clearManual", tab: "ftir", label: "Clear manual peaks", what: "Undoes all peaks you added or deleted by hand on this spectrum.", keywords: ["reset", "manual"] },

  { id: "ftir.peakFilter", tab: "ftir", label: "Filter assignment", what: "Shows only peaks whose assignment contains this text.", keywords: ["search peaks", "find"], helpTopic: "peaks-table" },
  { id: "ftir.lowConf", tab: "ftir", label: "Show low-confidence", what: "Also lists peaks whose best assignment is below the min score.", keywords: ["weak", "uncertain"], helpTopic: "peaks-table" },
  { id: "ftir.copyCsv", tab: "ftir", label: "Copy CSV", what: "Copies the peak table as CSV to the clipboard, ready to paste into Excel.", keywords: ["clipboard", "excel", "paste"] },
  { id: "ftir.labelChoice", tab: "ftir", label: "Assignment choice", what: "Pick which candidate labels this peak, keep Auto, or hide the label.", keywords: ["override", "relabel", "candidate"], helpTopic: "peaks-table" },
  { id: "ftir.labelText", tab: "ftir", label: "Plot label", what: "Your own text for this peak's label on the chart; empty uses the assignment.", keywords: ["rename", "custom label", "annotation"] },
  { id: "ftir.hideLabel", tab: "ftir", label: "Hide label", what: "Hides this peak's label on the chart (the peak stays in the table).", keywords: ["declutter", "overlap"] },

  {
    id: "plate.gridCsv",
    tab: "plate-reader",
    label: "MIC grid CSV",
    what: "Downloads the % growth per concentration for every compound's mean and replicates.",
    keywords: ["mic", "reading grid", "download"],
    panel: "plate.tab.experiment",
  },
];

const BY_ID = new Map(CONTROLS.map((c) => [c.id, c]));

export function getControl(id: string): ControlHint | undefined {
  return BY_ID.get(id);
}

export function tabOfRoute(pathname: string): ControlTab | null {
  const base = pathname.replace(/\/$/, "");
  const hit = (Object.keys(TAB_ROUTES) as ControlTab[]).find((t) => TAB_ROUTES[t] === base);
  return hit ?? null;
}
