// One entry per control: the hover hint, the Ctrl+K finder, tours and "Show me" all read this list.
// A test fails when a control in the UI has no entry here, or an entry is not used in the UI.

export type ControlTab = "lcms" | "ftir" | "plate-reader" | "ai" | "app";

export interface ControlHint {
  id: string;
  tab: ControlTab;
  label: string;
  what: string;
  typical?: string;
  keywords?: string[];
  // A panel/section that must be opened before the control is visible (see useRevealPanel).
  panel?: string;
  helpTopic?: string;
}

export const TAB_ROUTES: Record<ControlTab, string | null> = {
  lcms: "/lcms",
  ftir: "/ftir",
  "plate-reader": "/plate-reader",
  ai: "/ai",
  app: null,
};

export const TAB_LABELS: Record<ControlTab, string> = {
  lcms: "LCMS",
  ftir: "FTIR",
  "plate-reader": "Plate Reader",
  ai: "AI Assistant",
  app: "Everywhere",
};

export const CONTROLS: ControlHint[] = [
  {
    id: "app.help",
    tab: "app",
    label: "Help",
    what: "Opens the guide for this tab: what each part does, how results are calculated, and troubleshooting.",
    keywords: ["manual", "guide", "documentation", "f1"],
  },
  {
    id: "app.findControl",
    tab: "app",
    label: "Find a control",
    what: "Search every button and setting by name or purpose; Enter jumps to it and highlights it.",
    typical: "Ctrl+K (⌘K on a Mac)",
    keywords: ["search", "command", "where", "locate"],
  },
  {
    id: "app.experimentTag",
    tab: "app",
    label: "Experiment tag",
    what: "Groups files that belong to one experiment; tagged plates are combined in the Experiment view and the SI package.",
    typical: "e.g. \"MIC run 12\"",
    keywords: ["group", "link", "si package", "label"],
  },
  {
    id: "app.exportFigure",
    tab: "app",
    label: "Export figure",
    what: "Saves the chart for a paper or slides: 1:1 as on screen, or at a journal width, as SVG (vector) or PNG at the chosen DPI.",
    typical: "SVG, single column 85 mm, 600 DPI for PNG",
    keywords: ["save", "image", "png", "svg", "publication", "download"],
  },

  { id: "app.tryExample", tab: "app", label: "Try with example data", what: "Opens a ready-made example on this tab (marked \"Example\") with steps to try, so you can learn without your own files.", keywords: ["demo", "sample data", "practice", "tutorial", "example"] },
  { id: "app.workspace", tab: "app", label: "Lab member profile", what: "Each lab member's workspace keeps its own open files and settings. Switch to yours, or add a new member.", keywords: ["workspace", "user", "profile", "switch", "member"] },
  { id: "app.userMenu", tab: "app", label: "Profile menu", what: "Your profile, switching lab member, and the colour theme (day, night, night vision).", keywords: ["account", "settings", "menu"] },
  { id: "app.theme", tab: "app", label: "Theme", what: "Day, night or night-vision colours for the whole app; charts follow the theme on screen, exports stay white.", typical: "Day", keywords: ["dark mode", "night", "colours", "appearance"], panel: "app.menu" },
  { id: "app.pinSidebar", tab: "app", label: "Pin sidebar", what: "Keeps the navigation sidebar open; unpinned it collapses to icons and opens on hover.", keywords: ["navigation", "collapse"] },

  // AI Assistant
  { id: "ai.provider", tab: "ai", label: "Provider", what: "Which AI answers: Demo (offline keyword matching, no real model), OpenAI, Anthropic, or a local Ollama model.", typical: "Demo until a key or Ollama is set up", keywords: ["openai", "anthropic", "claude", "ollama", "model", "llm"], helpTopic: "providers" },
  { id: "ai.model", tab: "ai", label: "Model", what: "Model name for the chosen provider; leave the suggested one unless you know you need another.", keywords: ["gpt", "claude", "llama"], helpTopic: "providers" },
  { id: "ai.apiKey", tab: "ai", label: "API key", what: "Your provider key. It is kept in this browser in plain text and sent straight to the provider; use a key with a low spending cap.", keywords: ["key", "token", "secret"], helpTopic: "providers" },
  { id: "ai.ollamaUrl", tab: "ai", label: "Ollama URL", what: "Address of a local Ollama server, for models that run on your own computer.", typical: "http://127.0.0.1:11434", keywords: ["local model", "offline"], helpTopic: "providers" },
  { id: "ai.test", tab: "ai", label: "Test connection", what: "Checks that the provider, model and key work before you chat.", keywords: ["check", "verify"] },
  { id: "ai.includeContext", tab: "ai", label: "Include app context", what: "Sends a short summary of your open files and settings with each message, so answers refer to your data.", typical: "On", keywords: ["context", "data"], helpTopic: "context" },
  { id: "ai.focusModule", tab: "ai", label: "Focus module", what: "Which tab's context to send: automatic, or LCMS, FTIR or Plate Reader only.", typical: "auto", helpTopic: "context" },
  { id: "ai.sessions", tab: "ai", label: "Loaded sessions", what: "Tick files to narrow the context to them; with none ticked, all loaded files are included. Refresh re-reads the list after you open new files.", keywords: ["files", "select data", "refresh"], helpTopic: "context" },
  { id: "ai.autoExecute", tab: "ai", label: "Auto-execute safe actions", what: "Lets the assistant run harmless actions (open a dialog, make an EIC) without asking; risky ones still need your approval.", typical: "Off until you trust it", keywords: ["automation", "approve", "tools"] },
  { id: "ai.toolTrace", tab: "ai", label: "Show tool-call trace", what: "Shows each action the assistant ran, with its inputs, under the reply.", keywords: ["debug", "actions"] },
  { id: "ai.fallback", tab: "ai", label: "Provider fallback", what: "If the chosen provider fails, tries the next configured provider instead of stopping.", keywords: ["backup", "retry"] },
  { id: "ai.actionLog", tab: "ai", label: "Action log", what: "History of every action run by the assistant or macros, with filters by status, actor and time.", keywords: ["history", "audit"] },
  { id: "ai.savedPrompts", tab: "ai", label: "Saved prompts", what: "Questions you ask often: save the current message, then use it again or run it in one click.", keywords: ["templates", "favourites"] },
  { id: "ai.macros", tab: "ai", label: "Macros", what: "Record the actions the assistant runs, save them under a name, and replay them later without the AI.", keywords: ["record", "replay", "automation", "workflow"] },
  { id: "ai.starters", tab: "ai", label: "Example questions", what: "Click one to send it, e.g. make an EIC or open the Kendrick plot.", keywords: ["examples", "starter", "ideas"], helpTopic: "starter-prompts" },
  { id: "ai.message", tab: "ai", label: "Message", what: "Ask about your data or the app, or ask it to do something (e.g. \"create an EIC for m/z 150.1\"). Enter sends, Shift+Enter adds a line.", keywords: ["chat", "ask", "question"] },
  { id: "ai.export", tab: "ai", label: "Export conversation", what: "Saves this chat as a text file.", keywords: ["download", "save chat"] },
  { id: "ai.clear", tab: "ai", label: "Clear chat", what: "Removes all messages from this conversation.", keywords: ["reset", "new chat"] },

  // Plate Reader
  {
    id: "plate.open",
    tab: "plate-reader",
    label: "Open plate",
    what: "Loads a BioTek Gen5 export or any sheet/CSV with an 8×12 block labelled A–H and 1–12. You can also drop files on the page.",
    typical: ".xlsx from Gen5",
    keywords: ["upload", "import", "file", "gen5", "excel"],
    helpTopic: "files",
  },
  {
    id: "plate.view",
    tab: "plate-reader",
    label: "Plate map / Results / Experiment",
    what: "Plate map sets which wells are which; Results shows this plate's charts; Experiment combines plates with the same tag.",
    keywords: ["tabs", "switch", "view"],
    helpTopic: "overview",
  },
  {
    id: "plate.grid",
    tab: "plate-reader",
    label: "Plate wells",
    what: "Each well shows its OD. Click a well to exclude or include it; with a group picked below, drag across wells to assign them.",
    keywords: ["well", "exclude", "include", "contaminated", "paint", "drag", "od"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.paint",
    tab: "plate-reader",
    label: "Paint wells as",
    what: "Pick a compound, growth control, blank or unassigned, then drag across wells on the plate to give them that role.",
    keywords: ["assign", "brush", "role", "group", "drag"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.template",
    tab: "plate-reader",
    label: "Template",
    what: "Applies a saved layout (compounds, dilution, controls) to this plate. Templates are shared by the whole lab.",
    keywords: ["preset", "saved layout", "load"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.deleteTemplate",
    tab: "plate-reader",
    label: "Delete template",
    what: "Removes the selected template for everyone in the lab. Plates already using it keep their layout.",
    keywords: ["remove template"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.top",
    tab: "plate-reader",
    label: "Top concentration",
    what: "Concentration in the first dilution column; each next column is divided by the factor. Remembered for the next plate.",
    typical: "1024 µg/mL",
    keywords: ["highest", "start", "concentration", "dose"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.unit",
    tab: "plate-reader",
    label: "Unit",
    what: "Concentration unit shown on the plate, charts, tables and exports.",
    typical: "µg/mL",
    panel: "plate.tab.map",
  },
  {
    id: "plate.direction",
    tab: "plate-reader",
    label: "Direction",
    what: "Whether the dilution series runs across columns (compounds in rows) or down rows (compounds in columns).",
    typical: "Across columns",
    keywords: ["orientation", "rows", "columns"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.factor",
    tab: "plate-reader",
    label: "Dilution factor",
    what: "How much each step is diluted from the one before.",
    typical: "÷2 (two-fold dilution)",
    keywords: ["serial", "two-fold", "step"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.range",
    tab: "plate-reader",
    label: "Dilution columns",
    what: "First (top concentration) and last column of the dilution series.",
    typical: "1 to 11 (column 12 = growth control)",
    keywords: ["from", "to", "first", "last"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.compoundName",
    tab: "plate-reader",
    label: "Compound name",
    what: "Name used on charts, tables, exports and the Experiment view.",
    keywords: ["rename", "sample", "polymer"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.compoundRows",
    tab: "plate-reader",
    label: "Compound rows",
    what: "The replicate rows this compound fills, as a range or list. Press Apply to update the plate.",
    typical: "A–C",
    keywords: ["replicates", "lines", "where"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.compoundKind",
    tab: "plate-reader",
    label: "Kind",
    what: "Sample for the compounds you test; Reference for a known antibiotic such as gentamicin, marked as reference in charts.",
    typical: "Sample",
    keywords: ["reference", "control antibiotic", "gentamicin"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.removeCompound",
    tab: "plate-reader",
    label: "Remove compound",
    what: "Takes the compound out of the form; its wells become unassigned after Apply.",
    panel: "plate.tab.map",
  },
  {
    id: "plate.addCompound",
    tab: "plate-reader",
    label: "Add compound",
    what: "Adds a sample compound to the form; type its rows, then press Apply.",
    keywords: ["new compound", "sample"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.addReference",
    tab: "plate-reader",
    label: "Add reference",
    what: "Adds a reference antibiotic (named Gentamicin by default) to the form, for a control on the same plate.",
    keywords: ["gentamicin", "antibiotic", "positive control"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.growthControl",
    tab: "plate-reader",
    label: "Growth control column",
    what: "Wells with bacteria and no compound: 100% growth. Each compound uses the growth-control wells in its own rows.",
    typical: "12",
    keywords: ["gc", "positive", "untreated", "100%"],
    panel: "plate.tab.map",
    helpTopic: "calculation",
  },
  {
    id: "plate.blank",
    tab: "plate-reader",
    label: "Blank rows",
    what: "Medium-only wells; their mean OD is subtracted from every well. Leave empty when the plate has no blank.",
    typical: "G–H",
    keywords: ["background", "medium", "sterile", "subtract"],
    panel: "plate.tab.map",
    helpTopic: "calculation",
  },
  {
    id: "plate.apply",
    tab: "plate-reader",
    label: "Apply to plate",
    what: "Fills the plate from the form (compound rows, growth control, blank). Excluded wells stay excluded.",
    keywords: ["update", "fill", "layout"],
    panel: "plate.tab.map",
    helpTopic: "plate-map",
  },
  {
    id: "plate.saveTemplate",
    tab: "plate-reader",
    label: "Save as template",
    what: "Saves this plate's layout (without excluded wells) under a name, for anyone in the lab to apply to other plates.",
    keywords: ["preset", "reuse", "store layout"],
    panel: "plate.tab.map",
  },
  {
    id: "plate.subtractBlank",
    tab: "plate-reader",
    label: "Subtract blank",
    what: "Subtracts the mean OD of the blank wells from every well before averaging. Off: values are OD as read.",
    typical: "On when the plate has blank wells",
    keywords: ["background", "baseline", "medium"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.fit4pl",
    tab: "plate-reader",
    label: "4PL fit (IC₅₀)",
    what: "Fits a 4-parameter logistic curve to each compound's means and reports IC₅₀ ± SE, Hill slope and R².",
    typical: "Off; only meaningful when growth drops within the tested range",
    keywords: ["ic50", "sigmoid", "logistic", "curve", "hill"],
    panel: "plate.tab.results",
    helpTopic: "results",
  },
  {
    id: "plate.workbook",
    tab: "plate-reader",
    label: "Calculation workbook",
    what: "Excel file that redoes every step with live formulas from the raw plate, so you can check or change the numbers.",
    keywords: ["excel", "xlsx", "formulas", "audit", "reproduce"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.explain",
    tab: "plate-reader",
    label: "How is this calculated?",
    what: "Shows how this chart was calculated with this plate's wells and numbers, the automatic checks, and Excel steps to redo it.",
    keywords: ["explain", "method", "why", "checks", "trust"],
    panel: "plate.tab.results",
    helpTopic: "calculation",
  },
  {
    id: "plate.design",
    tab: "plate-reader",
    label: "Design",
    what: "Sets the chart title and axis labels used on screen and in exports.",
    keywords: ["title", "axis", "label", "style"],
    panel: "plate.tab.results",
  },
  {
    id: "plate.plateCsv",
    tab: "plate-reader",
    label: "Plate CSV",
    what: "Downloads the 8×12 plate as read (raw OD) as a CSV file.",
    keywords: ["raw", "download", "export"],
    panel: "plate.tab.results",
  },
  {
    id: "plate.resultsCsv",
    tab: "plate-reader",
    label: "Results CSV",
    what: "Downloads the results table: every replicate, n, mean, SD and % growth per compound and concentration.",
    keywords: ["table", "download", "export", "data"],
    panel: "plate.tab.results",
    helpTopic: "results",
  },
  {
    id: "plate.siPackage",
    tab: "plate-reader",
    label: "Download SI package",
    what: "Zip with methods text, tables and provenance for every plate with this experiment tag, for a paper's supporting information.",
    keywords: ["supporting information", "zip", "paper", "methods"],
    panel: "plate.tab.experiment",
    helpTopic: "experiment",
  },
  {
    id: "plate.exportAll",
    tab: "plate-reader",
    label: "Export all (Excel)",
    what: "One workbook with the MIC reading grid plus every plate's calculation sheets with live formulas.",
    keywords: ["excel", "xlsx", "workbook", "experiment"],
    panel: "plate.tab.experiment",
    helpTopic: "experiment",
  },
  // LCMS
  { id: "lcms.open", tab: "lcms", label: "Open mzML", what: "Loads one or more mzML files (MS1 scans are indexed on upload). You can also drop files on the page.", typical: ".mzML exported from the instrument", keywords: ["upload", "import", "file", "mzml"], helpTopic: "files-workspace" },
  { id: "lcms.loadWorkspace", tab: "lcms", label: "Load workspace", what: "Restores files and settings from a workspace JSON file saved earlier.", keywords: ["restore", "json"], helpTopic: "files-workspace" },
  { id: "lcms.saveWorkspace", tab: "lcms", label: "Save workspace", what: "Saves the open files and all settings to a JSON file you can load later or send to someone.", keywords: ["json", "store"], helpTopic: "files-workspace" },
  { id: "lcms.polarity", tab: "lcms", label: "Polarity", what: "Which scans to show: all, positive (ESI+), negative (ESI−), or both side by side (Dual). Polymer matching needs ESI+ or ESI−.", typical: "ESI+ for most polymers", keywords: ["positive", "negative", "esi", "ion mode", "dual"], helpTopic: "view-tab" },
  { id: "lcms.dualLayout", tab: "lcms", label: "Dual layout", what: "In Dual polarity, show positive and negative charts stacked or side by side.", typical: "Stacked", keywords: ["side by side", "columns"] },
  { id: "lcms.toolsSection", tab: "lcms", label: "Analysis / Display", what: "Analysis holds navigation, chromatograms, peak labels, polymer matching and exports; Display holds units, polarity, panels, region and overlays.", keywords: ["tools panel", "tabs"], helpTopic: "tools-panel" },
  { id: "lcms.collapseTools", tab: "lcms", label: "Collapse tools panel", what: "Hides the tools panel to give the charts more room; click again to bring it back.", keywords: ["hide panel", "expand", "more space"] },

  { id: "lcms.scanNav", tab: "lcms", label: "Scan navigation", what: "Steps to the previous/next MS1 scan or jumps to the first/last; the spectrum follows.", typical: "← / → keys", keywords: ["previous", "next", "first", "last", "scan"], panel: "lcms.tools.analysis", helpTopic: "navigate-tab" },
  { id: "lcms.eic", tab: "lcms", label: "EIC", what: "Builds an extracted ion chromatogram: the intensity of one m/z (± tolerance) over retention time.", keywords: ["extracted ion chromatogram", "xic", "m/z trace"], panel: "lcms.tools.analysis", helpTopic: "charts-eic" },
  { id: "lcms.findMz", tab: "lcms", label: "Find m/z", what: "Searches all scans for an m/z (± tolerance) and can move the RT cursor to the strongest match.", keywords: ["search mass", "sweep", "locate"], panel: "lcms.tools.analysis", helpTopic: "find-mz" },
  { id: "lcms.rtJump", tab: "lcms", label: "Jump to RT", what: "Moves to the MS1 scan nearest the retention time you type; press Enter or Go.", typical: "e.g. 2.45 min", keywords: ["retention time", "go to", "time"], panel: "lcms.tools.analysis", helpTopic: "navigate-tab" },
  { id: "lcms.annotateSpectrum", tab: "lcms", label: "Annotate spectrum peaks", what: "Labels the strongest spectrum peaks with their m/z.", typical: "On", keywords: ["labels", "m/z labels"], panel: "lcms.tools.analysis", helpTopic: "annotate-tab" },
  { id: "lcms.labelTopN", tab: "lcms", label: "Top N labels", what: "How many of the most intense peaks get an m/z label (also used by Export labels).", typical: "10", keywords: ["number of labels"], panel: "lcms.tools.analysis" },
  { id: "lcms.labelMinRel", tab: "lcms", label: "Min rel intensity", what: "Only peaks at least this fraction of the base peak get a label (0.05 = 5%).", typical: "0.05", keywords: ["threshold", "relative intensity"], panel: "lcms.tools.analysis" },
  { id: "lcms.dragLabels", tab: "lcms", label: "Drag labels", what: "Lets you move spectrum labels with the mouse to avoid overlaps; Reset positions puts them back.", keywords: ["move labels", "overlap"], panel: "lcms.tools.analysis" },
  { id: "lcms.polymerEnable", tab: "lcms", label: "Polymer/reaction matching", what: "Labels spectrum peaks that match the polymer series and reaction products set in Polymer Match. Needs ESI+ or ESI− polarity.", keywords: ["polymer", "oligomer", "series", "match"], panel: "lcms.tools.polymer", helpTopic: "polymer-controls" },
  { id: "lcms.polymerDialog", tab: "lcms", label: "Polymer Match", what: "Set monomers, end groups, adducts, charges and tolerance for matching polymer series in the spectrum.", keywords: ["monomer", "end group", "adduct", "oligomer"], panel: "lcms.tools.polymer", helpTopic: "polymer-controls" },
  { id: "lcms.expectedProducts", tab: "lcms", label: "Expected products", what: "Lists the expected monomer/dimer/trimer products and whether each is found in the current MS1 spectrum.", keywords: ["product", "dimer", "trimer", "find my product"], panel: "lcms.tools.polymer", helpTopic: "polymer-controls" },
  { id: "lcms.kendrick", tab: "lcms", label: "Kendrick plot", what: "Kendrick mass defect plot of the current spectrum: peaks of one repeat-unit series line up horizontally.", keywords: ["kmd", "mass defect", "series"], panel: "lcms.tools.polymer" },
  { id: "lcms.polymerDefaults", tab: "lcms", label: "Save as defaults", what: "Stores the current polymer settings as the starting point for newly opened files.", keywords: ["remember", "default settings"], panel: "lcms.tools.polymer" },
  { id: "lcms.featureTable", tab: "lcms", label: "Feature table", what: "Table of detected features (m/z, RT, intensity) for the file, with export.", keywords: ["features", "peak list", "table"], panel: "lcms.tools.analysis", helpTopic: "dialogs" },
  { id: "lcms.comparison", tab: "lcms", label: "Comparison", what: "Matrix comparing feature intensities across the open files.", keywords: ["compare samples", "matrix", "heatmap"], panel: "lcms.tools.analysis", helpTopic: "dialogs" },
  { id: "lcms.exportLabels", tab: "lcms", label: "Export labels (all scans)", what: "CSV of the top-N labelled peaks of every MS1 scan, using the Top N and Min rel intensity above.", keywords: ["csv", "all scans", "peak list"], panel: "lcms.tools.analysis", helpTopic: "exports" },

  { id: "lcms.showPolymerControls", tab: "lcms", label: "Show polymer matching", what: "Shows or hides the Polymer & reaction matching box in the Analysis tab.", keywords: ["extra controls"], panel: "lcms.tools.display" },
  { id: "lcms.rtUnit", tab: "lcms", label: "RT display unit", what: "How retention times are shown. The time unit stored in each mzML file is read automatically; this only changes the display.", typical: "minutes", keywords: ["seconds", "minutes", "time"], panel: "lcms.tools.display", helpTopic: "view-tab" },
  { id: "lcms.uvTimeUnit", tab: "lcms", label: "UV CSV time unit", what: "Time unit of the first column in attached UV/DAD CSV files. Auto reads it from the header (e.g. \"Time (sec)\"), else assumes minutes.", typical: "auto", keywords: ["uv", "dad", "seconds"], panel: "lcms.tools.display", helpTopic: "uv-csv" },
  { id: "lcms.panels", tab: "lcms", label: "Show TIC / spectrum / UV", what: "Shows or hides each chart.", keywords: ["hide chart", "panels"], panel: "lcms.tools.display" },
  { id: "lcms.regionSelect", tab: "lcms", label: "Region select", what: "Drag across the TIC to select an RT window; Sum RT window then sums all MS1 scans in it.", keywords: ["rt window", "drag", "sum", "range"], panel: "lcms.tools.display", helpTopic: "charts-tic" },
  { id: "lcms.ignoreMz", tab: "lcms", label: "Ignore m/z", what: "Masses (comma-separated) left out when scaling the summed region spectrum, e.g. a dominant contaminant.", typical: "e.g. 91.1, 113.0", keywords: ["contaminant", "exclude mass"], panel: "lcms.tools.display" },
  { id: "lcms.ignoreTol", tab: "lcms", label: "Ignore tolerance", what: "± m/z window around each ignored mass.", typical: "0.01", panel: "lcms.tools.display" },
  { id: "lcms.clearRegion", tab: "lcms", label: "Clear region", what: "Removes the selected RT window from the TIC.", panel: "lcms.tools.display" },
  { id: "lcms.overlays", tab: "lcms", label: "Overlays", what: "Draws the files ticked below on top of the current one: TICs, UV traces, spectra at the selected RT, or EICs.", keywords: ["compare", "overlay", "multiple files"], panel: "lcms.tools.display" },
  { id: "lcms.overlayFiles", tab: "lcms", label: "Files to overlay", what: "Tick the open files to include in the overlays; Clear unticks them all.", panel: "lcms.tools.display" },
  { id: "lcms.overlayLabels", tab: "lcms", label: "Labels for overlaid spectra", what: "Also labels peaks of the overlaid spectra, not only the current one.", panel: "lcms.tools.display" },
  { id: "lcms.exportCsv", tab: "lcms", label: "Data exports", what: "Spectrum CSV (current scan), UV CSV, TIC overlay CSV; Sum RT window loads the summed MS1 of the selected TIC region.", keywords: ["csv", "download", "sum"], panel: "lcms.tools.display", helpTopic: "exports" },

  { id: "lcms.createProject", tab: "lcms", label: "Create project", what: "Makes a folder to group related files in the sessions list.", keywords: ["folder", "group files"], helpTopic: "sessions-projects" },
  { id: "lcms.pinSessions", tab: "lcms", label: "Pin sessions panel", what: "Keeps the sessions list open beside the charts instead of opening on hover.", keywords: ["sidebar", "keep open"] },
  { id: "lcms.moveToProject", tab: "lcms", label: "Move to project", what: "Moves this file into a project folder.", keywords: ["organise", "folder"], helpTopic: "sessions-projects" },
  { id: "lcms.removeSession", tab: "lcms", label: "Remove file", what: "Closes this file and removes it from the workspace.", keywords: ["delete", "close"] },
  { id: "lcms.deleteProject", tab: "lcms", label: "Delete project", what: "Deletes the project folder; its files move back to the main list.", keywords: ["remove folder"] },

  { id: "lcms.ticTool", tab: "lcms", label: "Inspect / Slice peak", what: "Inspect: click the TIC to open that scan. Slice: drag across a peak to integrate its area between the two times.", keywords: ["integrate", "area", "slice", "click"], helpTopic: "charts-tic" },
  { id: "lcms.undoRedo", tab: "lcms", label: "Undo / redo", what: "Steps back or forward through region slices or EIC actions.", typical: "Ctrl+Z / Ctrl+Y" },
  { id: "lcms.overlayScale", tab: "lcms", label: "Overlay scale", what: "Raw = shared absolute scale; % Norm = each trace scaled to its base peak; Stacked = offset waterfall.", typical: "% Norm to compare shapes", keywords: ["normalize", "stacked", "waterfall"] },
  { id: "lcms.syncZoom", tab: "lcms", label: "Sync zoom", what: "Zooming or panning the TIC also moves the UV chromatogram, and the other way round.", keywords: ["link axes", "zoom together"] },
  { id: "lcms.chartDesign", tab: "lcms", label: "Design", what: "Chart appearance: titles, sizes, colours, axis limits and labels for this chart.", keywords: ["style", "graph settings", "appearance"], helpTopic: "graph-settings-detail" },
  { id: "lcms.reload", tab: "lcms", label: "Reload", what: "Redraws this chart, e.g. after resizing the window.", keywords: ["refresh", "redraw"] },
  { id: "lcms.integrateEic", tab: "lcms", label: "Integrate EIC", what: "Integrates the peak of each EIC and reports area, apex RT and height.", keywords: ["area", "quantify", "peak area"], helpTopic: "charts-eic" },
  { id: "lcms.clearEic", tab: "lcms", label: "Clear EICs", what: "Removes all EICs from the chart.", keywords: ["remove eic"] },
  { id: "lcms.resetLabels", tab: "lcms", label: "Reset label positions", what: "Moves all labels you dragged back to their default place.", keywords: ["undo drag", "labels"] },
  { id: "lcms.polymerStudio", tab: "lcms", label: "Polymer & Reaction Studio", what: "Side panel to tune polymer matching while watching the labels update live on the spectrum.", keywords: ["live", "tune", "polymer"], helpTopic: "polymer-controls" },
  { id: "lcms.deconvolution", tab: "lcms", label: "Deconvolution", what: "Converts a multiply-charged ESI envelope into neutral masses from charge states and isotope spacing.", keywords: ["charge state", "neutral mass", "zero charge", "envelope"], helpTopic: "dialogs" },
  { id: "lcms.targetMz", tab: "lcms", label: "Target m/z", what: "Type an m/z or pick a detected peak, then inspect it or create its EIC.", typical: "e.g. 524.3", keywords: ["mass", "inspect", "eic"] },
  { id: "lcms.spectrumMode", tab: "lcms", label: "Zoom / Move labels", what: "Zoom draws zoom boxes on the spectrum; Move labels lets you drag labels without zooming.", keywords: ["drag labels", "zoom box"] },
  { id: "lcms.spectrumOverlay", tab: "lcms", label: "Spectrum overlay mode", what: "How overlaid spectra are drawn: overlaid, butterfly (mirrored head-to-tail), butterfly %, or % normalised.", typical: "Butterfly to compare two samples", keywords: ["mirror", "head to tail", "compare"] },

  { id: "lcms.uvAutoLabel", tab: "lcms", label: "Auto label UV peaks", what: "Finds UV peaks and labels each with the main m/z of the MS spectrum at that time.", keywords: ["annotate uv", "uv peaks"], helpTopic: "charts-uv" },
  { id: "lcms.uvLabelRt", tab: "lcms", label: "Label RT", what: "Labels the selected UV retention time with the top MS peaks of that scan.", keywords: ["annotate"] },
  { id: "lcms.uvCustomLabel", tab: "lcms", label: "Custom UV label", what: "Adds your own text label at the selected retention time.", keywords: ["text", "annotation"] },
  { id: "lcms.uvLabelOptions", tab: "lcms", label: "UV label options", what: "Peak detection thresholds, label orientation and snapping, MS transfer, grouping and UV↔MS alignment.", keywords: ["settings", "uv labels"], helpTopic: "charts-uv" },
  { id: "lcms.uvClearLabels", tab: "lcms", label: "Clear UV labels", what: "Deletes all transferred and custom UV labels.", keywords: ["remove labels"] },
  { id: "lcms.uvAttach", tab: "lcms", label: "Attach UV CSV", what: "Adds a UV/DAD chromatogram exported from your LC software (CSV with time and signal) to show beside the TIC.", typical: "CSV: time, absorbance", keywords: ["dad", "uv", "detector", "import"], helpTopic: "uv-csv" },
  { id: "lcms.uvDetach", tab: "lcms", label: "Detach UV", what: "Removes the attached UV chromatogram from this file.", keywords: ["remove uv"] },
  { id: "lcms.uvArrange", tab: "lcms", label: "Auto-arrange stairs", what: "Rearranges UV labels into descending stairs so they don't overlap.", keywords: ["overlap", "tidy labels"], panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvProminence", tab: "lcms", label: "UV peak threshold", what: "Smallest UV peak that is detected, as a fraction of the tallest UV peak (0.05 = 5%).", typical: "0.05", keywords: ["threshold", "detection"], panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvMinDistance", tab: "lcms", label: "UV min distance", what: "Minimum time between two detected UV peaks.", typical: "0.2 min", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvRerun", tab: "lcms", label: "Re-run detection", what: "Detects and labels UV peaks again with the thresholds above.", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvOrientation", tab: "lcms", label: "Label orientation", what: "Vertical (−90°) or horizontal label text.", typical: "Vertical", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvSnap", tab: "lcms", label: "Snap to peak apex", what: "Moves each label to the top of the nearest UV peak.", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvTransfer", tab: "lcms", label: "Transfer MS peaks on click", what: "Clicking the UV trace labels that time with the top MS peaks.", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvTransferCount", tab: "lcms", label: "Peaks to transfer", what: "How many MS peaks go into each transferred label.", typical: "3", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvBunch", tab: "lcms", label: "Bunch identical labels", what: "Joins labels with the same text to one hub instead of repeating them.", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvHub", tab: "lcms", label: "Hub height", what: "Height of the bunching hub as a fraction of the plot (0–1).", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvStairX", tab: "lcms", label: "Stair step", what: "Horizontal spacing between stair-arranged labels.", typical: "0.08", panel: "lcms.uv.labelOptions" },
  { id: "lcms.uvOffset", tab: "lcms", label: "UV↔MS offset", what: "Time shift applied to the UV trace so its peaks line up with the TIC (detector delay). Apply Offset to use it.", typical: "0.000 min", keywords: ["delay", "align", "shift"], panel: "lcms.uv.labelOptions", helpTopic: "uv-csv" },
  { id: "lcms.uvAutoAlign", tab: "lcms", label: "Auto-align UV↔MS", what: "Finds the offset automatically by cross-correlating the TIC and UV traces; Enable keeps doing it for new files.", keywords: ["delay", "cross-correlation"], panel: "lcms.uv.labelOptions" },

  // LCMS dialogs
  { id: "lcms.polyTargetFile", tab: "lcms", label: "Target file", what: "Polymer settings are kept per mzML file; this picks the file you are editing.", keywords: ["per file", "which file"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyCopyFrom", tab: "lcms", label: "Copy from file", what: "Copies the polymer settings of another open file into this one.", keywords: ["reuse settings"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyApplyAll", tab: "lcms", label: "Apply to all open files", what: "Uses this file's polymer settings for every open mzML file.", panel: "lcms.dialog.polymer" },
  { id: "lcms.polyEnable", tab: "lcms", label: "Enable polymer matching", what: "Labels spectrum peaks that match the compositions set below. Needs ESI+ or ESI− polarity.", panel: "lcms.dialog.polymer", helpTopic: "polymer-controls" },
  { id: "lcms.polyPreset", tab: "lcms", label: "Small-oligomer preset", what: "Turns on matching, water loss, 2M clusters and the common adducts of this polarity (Na/K, or Cl/formate/acetate).", keywords: ["quick start", "defaults"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyTolerance", tab: "lcms", label: "Tolerance", what: "How close a peak must be to the predicted m/z to count as a match.", typical: "0.02 Da; 10–20 ppm for high-res, 0.05–0.2 Da for low-res data", keywords: ["ppm", "mass accuracy", "window"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyTolUnit", tab: "lcms", label: "Tolerance unit", what: "Da = the same window at every m/z; ppm = a window that grows with m/z.", typical: "Da", panel: "lcms.dialog.polymer" },
  { id: "lcms.polyMaxDp", tab: "lcms", label: "Max DP", what: "Largest number of monomer units in a composition. Large values with many monomers make the search slow.", typical: "12; 3–6 while testing", keywords: ["degree of polymerization", "chain length", "oligomer size"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyMinRel", tab: "lcms", label: "Min rel intensity", what: "Peaks below this fraction of the base peak are ignored by matching (0.01 = 1%).", typical: "0.01", keywords: ["threshold", "noise"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyMonomers", tab: "lcms", label: "Monomers", what: "Tick the hydroxy acids and amino acids that can be in your product; the abbreviation is used in labels (e.g. 2-GA + 1-His).", keywords: ["building blocks", "lactic acid", "glycolic", "amino acid", "abbreviation"], panel: "lcms.dialog.polymer", helpTopic: "polymer-controls" },
  { id: "lcms.polyOtherMonomers", tab: "lcms", label: "Other monomers", what: "Monomers not in the lists, one per line as \"Name Mass\", \"Name,Mass\" or just \"Mass\" (monoisotopic).", typical: "PEG 44.0262", keywords: ["custom monomer", "repeat unit"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyAdducts", tab: "lcms", label: "Adducts", what: "Extra ion types to look for besides [M+H]⁺ / [M−H]⁻. These are matched as singly charged ions only.", typical: "Na and K in ESI+", keywords: ["sodium", "potassium", "chloride", "formate", "acetate"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyCustomAdducts", tab: "lcms", label: "Custom adducts", what: "Your own adduct with name, total mass and charge; quick presets such as NH4, Li, Ca, TFA.", keywords: ["ammonium", "nh4", "lithium"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyBondDelta", tab: "lcms", label: "Per-bond delta", what: "Mass change per bond between monomers, added (DP − 1) times. Condensation (ester/amide) loses water per bond.", typical: "−18.010565 (condensation); 0 for addition polymers", keywords: ["water loss per bond", "condensation", "linkage"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyExtraDelta", tab: "lcms", label: "Extra delta", what: "A fixed mass added once to every composition, e.g. end groups or an initiator.", typical: "0", keywords: ["end group", "initiator"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyAdductMass", tab: "lcms", label: "H adduct mass", what: "Mass of the proton added (ESI+) or removed (ESI−) per charge.", typical: "1.007276 / −1.007276", panel: "lcms.dialog.polymer" },
  { id: "lcms.polyClusterMass", tab: "lcms", label: "Cluster adduct mass", what: "Adduct mass used for noncovalent 2M dimers when that variant is on.", typical: "1.007276 (2M+H)", keywords: ["dimer", "2m"], panel: "lcms.dialog.polymer" },
  { id: "lcms.polyCharges", tab: "lcms", label: "Allowed charge states", what: "Charges to try; each gives m/z = (M + z·1.007276) / z, labelled [M+zH]^z+.", typical: "1; \"1, 2\" for larger oligomers", keywords: ["charge", "z", "multiply charged"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyVariants", tab: "lcms", label: "Variants", what: "Also match each composition after water loss, CO₂ loss, oxidation (+O), or as a noncovalent 2M dimer.", keywords: ["decarboxylation", "oxidation", "dimer", "water loss"], panel: "lcms.dialog.polymer", helpTopic: "polymer-math" },
  { id: "lcms.polyReset", tab: "lcms", label: "Reset polymer settings", what: "Goes back to your saved defaults (factory defaults if none are saved).", panel: "lcms.dialog.polymer" },
  { id: "lcms.expMaxOligomer", tab: "lcms", label: "Max oligomer size", what: "Largest product to list: 1 = monomers, 2 = dimers, 3 = trimers, and so on.", typical: "3", keywords: ["dimer", "trimer"], panel: "lcms.dialog.expected" },
  { id: "lcms.expResolution", tab: "lcms", label: "Resolution mode", what: "Normal uses your polymer tolerance; Low resolution widens it to at least the low-res tolerance for unit-resolution data.", typical: "Normal", keywords: ["low res", "quadrupole"], panel: "lcms.dialog.expected" },
  { id: "lcms.expLowResTol", tab: "lcms", label: "Low-res tolerance", what: "Smallest matching window in low-resolution mode; a wider configured tolerance still wins.", typical: "0.15 Da", panel: "lcms.dialog.expected" },
  { id: "lcms.expShowUnmatched", tab: "lcms", label: "Show unmatched candidates", what: "Also lists expected products that were not found in the spectrum.", panel: "lcms.dialog.expected" },
  { id: "lcms.expExport", tab: "lcms", label: "Export expected products", what: "CSV of matched products for this scan, or for every TIC scan above the chosen % of the highest TIC.", keywords: ["csv", "download"], panel: "lcms.dialog.expected" },
  { id: "lcms.kmdRepeat", tab: "lcms", label: "Repeat unit", what: "Mass of the repeating unit that defines the Kendrick scale; members of one series then line up horizontally.", keywords: ["kendrick", "series"], panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdCustomMass", tab: "lcms", label: "Custom repeat mass", what: "Your own repeat mass when it is not one of the monomers. It's rounded to a nominal mass, so 14.5 behaves like 15.", panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdMinInt", tab: "lcms", label: "Min intensity", what: "Peaks below this % of the base peak are left off the plot.", typical: "1%", panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdTolerance", tab: "lcms", label: "Series tolerance", what: "How close in KMD (or ppm of m/z) points must be to join a series line.", typical: "0.01 KMD or 20 ppm", panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdMinPoints", tab: "lcms", label: "Min line points", what: "Smallest number of peaks that counts as a series.", typical: "3", panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdXAxis", tab: "lcms", label: "X axis", what: "Plot against m/z or Kendrick nominal mass.", typical: "m/z", panel: "lcms.dialog.kendrick" },
  { id: "lcms.kmdLabelSeries", tab: "lcms", label: "Label series points", what: "Labels the points of each detected series on the plot.", panel: "lcms.dialog.kendrick" },
  { id: "lcms.decCharges", tab: "lcms", label: "Charge range", what: "Lowest and highest charge state to consider when grouping peaks into one neutral mass.", typical: "1 to 8", keywords: ["z", "charge states"], panel: "lcms.dialog.deconvolution" },
  { id: "lcms.decTolerance", tab: "lcms", label: "Deconvolution tolerance", what: "How close a peak must be to the predicted m/z of a charge state.", typical: "0.02 Da or 20 ppm", panel: "lcms.dialog.deconvolution" },
  { id: "lcms.decMinInt", tab: "lcms", label: "Min intensity", what: "Peaks below this % of the base peak are ignored.", typical: "1%", panel: "lcms.dialog.deconvolution" },
  { id: "lcms.decEics", tab: "lcms", label: "Create EICs", what: "Builds an EIC for every charge state of this component.", panel: "lcms.dialog.deconvolution" },
  { id: "lcms.cmpValue", tab: "lcms", label: "Value", what: "Compare samples by peak area or peak height of each feature.", typical: "Peak area", panel: "lcms.dialog.comparison" },
  { id: "lcms.cmpGroup", tab: "lcms", label: "Group rows by", what: "Evidence/label first puts rows with the same expected product or label together; rows without one, or m/z only mode, group by the tolerance below.", typical: "Evidence/label first", panel: "lcms.dialog.comparison" },
  { id: "lcms.cmpTol", tab: "lcms", label: "m/z grouping tolerance", what: "Features within this m/z window are treated as the same row.", typical: "0.05", panel: "lcms.dialog.comparison" },
  { id: "lcms.dialogExport", tab: "lcms", label: "Export CSV", what: "Downloads this table as CSV.", keywords: ["download", "table"] },
  { id: "lcms.ftClear", tab: "lcms", label: "Clear table", what: "Removes all features from the table.", panel: "lcms.dialog.featureTable" },
  { id: "lcms.dialogTargetMz", tab: "lcms", label: "Target m/z", what: "The m/z to search for or to extract as a chromatogram.", typical: "e.g. 524.3", panel: "lcms.dialog.eic" },
  { id: "lcms.dialogTolerance", tab: "lcms", label: "m/z tolerance", what: "Window around the target m/z, in Da or ppm.", typical: "0.01 Da or 10 ppm", panel: "lcms.dialog.eic" },

  // FTIR
  { id: "ftir.open", tab: "ftir", label: "Open FTIR files", what: "Loads one or more spectra (CSV, TXT/TSV, JCAMP-DX, SPC). You can also drop files on the page.", typical: ".csv or .jdx", keywords: ["upload", "import", "spectrum"], helpTopic: "files-workspace" },
  { id: "ftir.loadWorkspace", tab: "ftir", label: "Load workspace", what: "Restores spectra and settings from a workspace JSON file saved earlier.", keywords: ["restore", "json", "session"], helpTopic: "files-workspace" },
  { id: "ftir.saveWorkspace", tab: "ftir", label: "Save workspace", what: "Saves the open spectra and all settings to a JSON file you can load later or send to someone.", keywords: ["json", "store", "session"], helpTopic: "files-workspace" },
  { id: "ftir.exportPeaks", tab: "ftir", label: "Export peaks CSV", what: "Downloads the picked peaks with wavenumber, height, prominence and assignments.", keywords: ["table", "download", "csv"], helpTopic: "peaks-table" },
  { id: "ftir.exportJdx", tab: "ftir", label: "Export JDX", what: "Saves the processed spectrum as JCAMP-DX, readable by most spectroscopy software.", keywords: ["jcamp", "download", "spectrum file"] },
  { id: "ftir.report", tab: "ftir", label: "Report HTML", what: "Downloads a printable HTML page with the preprocessing settings and the peak/assignment table (no chart image).", keywords: ["print", "summary", "pdf"] },
  { id: "ftir.inspector", tab: "ftir", label: "Analysis sections", what: "Switches the right panel between Preprocess, Peaks & library, Deconvolution and Multi-overlay.", keywords: ["panel", "tabs", "sections"] },
  { id: "ftir.undoRedo", tab: "ftir", label: "Undo / redo", what: "Steps back or forward through changes to the settings in this section.", typical: "Ctrl+Z / Ctrl+Y", keywords: ["revert", "back"] },

  { id: "ftir.preset", tab: "ftir", label: "Preprocessing preset", what: "Fills smoothing, baseline and normalisation with settings suited to the sample type.", typical: "KBr disc, ATR sample, Polymer thin film, Raw film", keywords: ["sample type", "defaults", "kbr", "atr", "film"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.mode", tab: "ftir", label: "Mode", what: "Whether the file is absorbance or transmittance. Transmittance is converted to absorbance (A = −log₁₀T) before any other step.", typical: "Detected from the file", keywords: ["absorbance", "transmittance", "%t"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.smoothing", tab: "ftir", label: "Smoothing window", what: "Savitzky–Golay smoothing over this many points; 0 = off. Larger windows remove noise but broaden sharp bands.", typical: "0 (off) or 5", keywords: ["savgol", "noise", "smooth"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.polyOrder", tab: "ftir", label: "SavGol poly order", what: "Polynomial order of the smoothing; higher keeps peak shapes better but smooths less.", typical: "2", keywords: ["savitzky", "polynomial"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.baseline", tab: "ftir", label: "Baseline", what: "How the sloping background is removed: airPLS / AsLS (automatic, flexible), rubberband (convex hull), polyfit, or none.", typical: "airPLS", keywords: ["background", "correction", "airpls", "asls", "rubberband"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.normalize", tab: "ftir", label: "Normalize", what: "Scales each spectrum so samples can be compared: max (tallest peak = 1), area, vector, SNV, min-max, or none.", typical: "none for one sample; SNV or vector to compare", keywords: ["scale", "snv", "vector", "compare"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.baselineLambda", tab: "ftir", label: "Baseline lambda", what: "How stiff the AsLS/airPLS baseline is. Higher = smoother baseline that ignores broad bands; too low cuts into peaks.", typical: "1e5 (range 1e4–1e7)", keywords: ["stiffness", "smoothness", "airpls", "asls"], panel: "ftir.inspector.preprocess", helpTopic: "reprocess" },
  { id: "ftir.asymmetry", tab: "ftir", label: "Asymmetry p", what: "AsLS only: how strongly the baseline stays under the peaks. Smaller = hugs the bottom more.", typical: "0.01 (range 0.001–0.1)", keywords: ["asls", "p"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.maskCo2", tab: "ftir", label: "Mask CO₂", what: "Excludes the CO₂ doublet (2310–2390 cm⁻¹) from peak picking and shades it. Water-vapour lines can't be masked; use background subtraction.", typical: "On if the CO₂ band shows", keywords: ["atmospheric", "co2", "carbon dioxide"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.atr", tab: "ftir", label: "ATR correction", what: "Approximate ATR correction: scales intensity by ν/ν_ref, since penetration depth grows at low wavenumber. Not a full optical correction.", typical: "On for ATR measurements", keywords: ["attenuated total reflectance", "penetration"], panel: "ftir.inspector.preprocess" },
  { id: "ftir.atrN", tab: "ftir", label: "ATR crystal index", what: "Refractive index of the ATR crystal, used by the ATR correction.", typical: "1.5; diamond/ZnSe 2.4, Ge 4.0", keywords: ["refractive", "diamond", "germanium", "znse"], panel: "ftir.inspector.preprocess" },

  { id: "ftir.pickPeaks", tab: "ftir", label: "Pick peaks", what: "Finds peaks with the settings below and, when Assign bonds is on, labels them from the bond library.", typical: "Shortcut P", keywords: ["detect", "find peaks", "run"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.pickOverlay", tab: "ftir", label: "Pick on overlaid spectra", what: "Also picks peaks on every spectrum shown in the overlay (needs 2 or more overlaid).", keywords: ["all spectra", "batch"], panel: "ftir.inspector.peaks" },
  { id: "ftir.minProminence", tab: "ftir", label: "Min prominence", what: "How far a peak must stand out from its surroundings. Raise it if you get too many small peaks.", typical: "0.01", keywords: ["threshold", "noise", "sensitivity"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.minHeight", tab: "ftir", label: "Min height", what: "Optional absolute cut-off: peaks below this y-value (after preprocessing) are ignored. Empty = off.", typical: "off", keywords: ["threshold", "cutoff"], panel: "ftir.inspector.peaks" },
  { id: "ftir.minDistance", tab: "ftir", label: "Min distance", what: "Minimum spacing between two picked peaks, so one band isn't picked twice.", typical: "8 cm⁻¹", keywords: ["spacing", "separation", "duplicate"], panel: "ftir.inspector.peaks" },
  { id: "ftir.topN", tab: "ftir", label: "Top N peaks", what: "Keeps only the N most prominent peaks; 0 keeps all.", typical: "15", keywords: ["limit", "number of peaks", "max"], panel: "ftir.inspector.peaks" },
  { id: "ftir.assign", tab: "ftir", label: "Assign bonds", what: "Labels each peak with likely functional groups from the bundled bond library (v3).", typical: "On", keywords: ["library", "functional group", "label", "identify"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.shoulder", tab: "ftir", label: "Shoulder mode", what: "Uses second-derivative minima to also find shoulders and overlapping bands that are not separate maxima.", typical: "Off; on for crowded regions such as amide I", keywords: ["2nd derivative", "overlapping", "hidden"], panel: "ftir.inspector.peaks", helpTopic: "peak-pick" },
  { id: "ftir.assignTopN", tab: "ftir", label: "Assign top N", what: "How many candidate assignments are kept per peak (shown in the label menu of the peak table).", typical: "3", keywords: ["candidates", "alternatives"], panel: "ftir.inspector.peaks" },
  { id: "ftir.assignMinScore", tab: "ftir", label: "Assign min score", what: "Candidates scoring below this (0–100) are hidden; if none pass, the best one is shown as low confidence.", typical: "35", keywords: ["confidence", "threshold", "score"], panel: "ftir.inspector.peaks" },
  { id: "ftir.relabel", tab: "ftir", label: "Apply & re-label", what: "Re-runs peak picking and library assignment with the exclusions below.", keywords: ["reassign", "update labels"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.excludeCategories", tab: "ftir", label: "Exclude categories", what: "Rule out functional-group families you know are absent (e.g. amide in a polyester), so they're never suggested.", keywords: ["rule out", "constraints", "functional group"], panel: "ftir.inspector.peaks", helpTopic: "assignments" },
  { id: "ftir.excludeSubcategories", tab: "ftir", label: "Exclude subcategories", what: "Rule out finer groups (e.g. primary amide) while keeping the rest of their family.", keywords: ["rule out", "constraints"], panel: "ftir.inspector.peaks" },
  { id: "ftir.ambiguity", tab: "ftir", label: "Ambiguity ratio", what: "A label is set automatically only if the best candidate scores at least this many times the runner-up; otherwise it's marked ambiguous.", typical: "1.3", keywords: ["confidence", "ambiguous", "runner-up"], panel: "ftir.inspector.peaks" },

  { id: "ftir.integrateRegion", tab: "ftir", label: "Integration region", what: "Wavenumber range of the band to integrate (low and high limit).", typical: "1700–1750 cm⁻¹ (carbonyl)", keywords: ["band", "limits", "area"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.integrateBaseline", tab: "ftir", label: "Integration baseline", what: "Line under the band: linear (between the region ends), horizontal (at the lower end), or tangent (between the lowest points near each end).", typical: "linear", keywords: ["area", "background"], panel: "ftir.inspector.quant" },
  { id: "ftir.integrate", tab: "ftir", label: "Integrate", what: "Measures the band's area, height, FWHM and peak position in the chosen region.", keywords: ["area", "quantify", "band"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.subtractSession", tab: "ftir", label: "Subtract session", what: "The spectrum to subtract from the current one (e.g. a solvent, substrate or unreacted starting material).", keywords: ["difference", "reference", "background"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractK", tab: "ftir", label: "Scale k", what: "Difference = current − k × other. Adjust k until the shared bands cancel.", typical: "1", keywords: ["factor", "difference"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractAutoFit", tab: "ftir", label: "Auto-fit region", what: "Finds k automatically by best cancelling the two spectra in the fit region below.", keywords: ["automatic k", "least squares"], panel: "ftir.inspector.quant" },
  { id: "ftir.subtractRegion", tab: "ftir", label: "Subtraction fit region", what: "Wavenumber range used to fit k, ideally where only the subtracted component absorbs.", typical: "1000–1800 cm⁻¹", panel: "ftir.inspector.quant" },
  { id: "ftir.subtract", tab: "ftir", label: "Subtract", what: "Shows the difference spectrum (current − k × other) on the chart.", keywords: ["difference spectrum"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearDifference", tab: "ftir", label: "Clear difference", what: "Removes the difference spectrum from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.matchRegion", tab: "ftir", label: "Match region", what: "Wavenumber range compared against the built-in reference spectra.", typical: "650–1800 cm⁻¹", keywords: ["fingerprint"], panel: "ftir.inspector.quant" },
  { id: "ftir.matchDerivative", tab: "ftir", label: "Match derivative", what: "Compares spectra as-is (0) or as 1st/2nd derivatives, which ignore baseline differences and sharpen bands.", typical: "1st", keywords: ["correlation", "derivative"], panel: "ftir.inspector.quant" },
  { id: "ftir.matchTopN", tab: "ftir", label: "Match top N", what: "How many best-matching references to list.", typical: "8", panel: "ftir.inspector.quant" },
  { id: "ftir.match", tab: "ftir", label: "Match references", what: "Ranks the built-in reference spectra by Pearson correlation with this spectrum; click a hit to overlay it.", keywords: ["identify", "library", "compare", "polymer"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearReference", tab: "ftir", label: "Clear reference", what: "Removes the overlaid reference spectrum from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.fitPresets", tab: "ftir", label: "Fit presets", what: "Sets region, number of components and profile for common bands: amide I, carbonyl, O–H/N–H.", keywords: ["amide", "carbonyl", "secondary structure"], panel: "ftir.inspector.quant" },
  { id: "ftir.fitRegion", tab: "ftir", label: "Fit region", what: "Wavenumber range to deconvolute into sub-bands.", typical: "1600–1700 cm⁻¹ (amide I)", panel: "ftir.inspector.quant" },
  { id: "ftir.fitComponents", tab: "ftir", label: "Components", what: "Number of sub-bands to fit; start positions come from second-derivative minima. Too many gives unstable fits.", typical: "2–4", keywords: ["sub-bands", "peaks"], panel: "ftir.inspector.quant" },
  { id: "ftir.fitProfile", tab: "ftir", label: "Profile", what: "Band shape for each component: Gaussian, Lorentzian or a 50/50 Voigt mix.", typical: "Gaussian", keywords: ["shape", "voigt", "lorentz"], panel: "ftir.inspector.quant" },
  { id: "ftir.deconvolute", tab: "ftir", label: "Deconvolute", what: "Fits the components and reports each centre, FWHM, area and area %, with R² of the fit.", keywords: ["fit", "secondary structure", "sub-band"], panel: "ftir.inspector.quant", helpTopic: "constraints-quant" },
  { id: "ftir.clearFit", tab: "ftir", label: "Clear fit", what: "Removes the fitted components from the chart.", panel: "ftir.inspector.quant" },
  { id: "ftir.fitCsv", tab: "ftir", label: "Fit components CSV", what: "Downloads the fitted components: centre, assignment, FWHM, amplitude, area and area %.", keywords: ["download", "export fit"], panel: "ftir.inspector.quant" },

  { id: "ftir.overlayShow", tab: "ftir", label: "Show selected spectra", what: "Draws the spectra ticked below on the same chart.", typical: "Shortcut O", keywords: ["compare", "overlay", "multiple"], panel: "ftir.inspector.overlay", helpTopic: "overlay" },
  { id: "ftir.overlayMode", tab: "ftir", label: "Overlay mode", what: "overlay = on top of each other; offset = shifted up a little each; stacked = separate bands of the chart.", typical: "overlay", keywords: ["stack", "offset"], panel: "ftir.inspector.overlay" },
  { id: "ftir.overlaySelect", tab: "ftir", label: "Spectra to overlay", what: "Tick the open spectra to draw together with the current one.", panel: "ftir.inspector.overlay" },

  { id: "ftir.secondDerivative", tab: "ftir", label: "2nd derivative", what: "Overlays the inverted 2nd derivative (−d²A/dν²) to reveal hidden sub-bands and shoulders.", keywords: ["shoulders", "hidden bands"], helpTopic: "spectrum-chart" },
  { id: "ftir.showBaseline", tab: "ftir", label: "Show baseline", what: "Draws the fitted baseline that is subtracted, so you can check it follows the background and not the peaks.", keywords: ["background", "check baseline"], helpTopic: "spectrum-chart" },
  { id: "ftir.region", tab: "ftir", label: "Wavenumber region", what: "Zooms the chart to a preset range or your own limits.", typical: "Full 400–4000 cm⁻¹; Amide I & II 1500–1750", keywords: ["zoom", "range", "fingerprint", "axis"], helpTopic: "spectrum-chart" },
  { id: "ftir.design", tab: "ftir", label: "Design", what: "Opens chart display settings: line width, frame, grid, peak labels, font sizes and trace colours.", keywords: ["style", "appearance", "graph settings"], helpTopic: "spectrum-chart" },
  { id: "ftir.lineWidth", tab: "ftir", label: "Line width", what: "Thickness of the spectrum lines, on screen and in exports.", typical: "1.4", panel: "ftir.chart.design" },
  { id: "ftir.frame", tab: "ftir", label: "Frame", what: "Axis box around the plot: none, half (left and bottom axes) or full.", typical: "Half frame", panel: "ftir.chart.design" },
  { id: "ftir.ticks", tab: "ftir", label: "Show ticks", what: "Shows tick marks on the axes.", typical: "On", panel: "ftir.chart.design" },
  { id: "ftir.grid", tab: "ftir", label: "Show grid", what: "Shows grid lines behind the spectrum.", typical: "On", panel: "ftir.chart.design" },
  { id: "ftir.groupRegions", tab: "ftir", label: "Group regions", what: "Shades the typical wavenumber ranges of common functional groups behind the spectrum.", typical: "Off · shortcut F", keywords: ["functional groups", "bands", "shading"], panel: "ftir.chart.design" },
  { id: "ftir.labelColor", tab: "ftir", label: "Peak label colour", what: "Colour of the peak labels on the chart.", panel: "ftir.chart.design" },
  { id: "ftir.labelSize", tab: "ftir", label: "Peak label size", what: "Font size of the peak labels.", typical: "10", panel: "ftir.chart.design" },
  { id: "ftir.axisTitleSize", tab: "ftir", label: "Axis title size", what: "Font size of the axis titles.", typical: "13", panel: "ftir.chart.design" },
  { id: "ftir.axisTickSize", tab: "ftir", label: "Axis tick size", what: "Font size of the axis numbers.", typical: "12", panel: "ftir.chart.design" },
  { id: "ftir.traceColors", tab: "ftir", label: "Trace colours", what: "Colour of each spectrum on the chart and in exports.", keywords: ["colour", "color", "line colour"], panel: "ftir.chart.design" },
  { id: "ftir.peakTool", tab: "ftir", label: "Peak tool", what: "Inspect shows values on hover; Add places a peak where you click; Delete removes the peak you click.", keywords: ["manual peak", "add peak", "remove peak", "click"], helpTopic: "peak-pick" },
  { id: "ftir.clearManual", tab: "ftir", label: "Clear manual peaks", what: "Undoes all peaks you added or deleted by hand on this spectrum.", keywords: ["reset", "manual"] },

  { id: "ftir.peakFilter", tab: "ftir", label: "Filter assignment", what: "Shows only peaks whose assignment contains this text.", keywords: ["search peaks", "find"], helpTopic: "peaks-table" },
  { id: "ftir.lowConf", tab: "ftir", label: "Show low-confidence", what: "Also lists peaks whose best assignment is below the min score.", keywords: ["weak", "uncertain"], helpTopic: "peaks-table" },
  { id: "ftir.copyCsv", tab: "ftir", label: "Copy CSV", what: "Copies the peak table as CSV to the clipboard, ready to paste into Excel.", keywords: ["clipboard", "excel", "paste"] },
  { id: "ftir.labelChoice", tab: "ftir", label: "Assignment choice", what: "Pick which candidate labels this peak, keep Auto, or hide the label.", keywords: ["override", "relabel", "candidate"], helpTopic: "peaks-table" },
  { id: "ftir.labelText", tab: "ftir", label: "Plot label", what: "Your own text for this peak's label on the chart; empty uses the assignment.", keywords: ["rename", "custom label", "annotation"] },
  { id: "ftir.hideLabel", tab: "ftir", label: "Hide label", what: "Hides this peak's label on the chart (the peak stays in the table).", keywords: ["declutter", "overlap"] },

  {
    id: "plate.gridCsv",
    tab: "plate-reader",
    label: "MIC grid CSV",
    what: "Downloads the % growth per concentration for every compound's mean and replicates.",
    keywords: ["mic", "reading grid", "download"],
    panel: "plate.tab.experiment",
  },
];

const BY_ID = new Map(CONTROLS.map((c) => [c.id, c]));

export function getControl(id: string): ControlHint | undefined {
  return BY_ID.get(id);
}

export function tabOfRoute(pathname: string): ControlTab | null {
  const base = pathname.replace(/\/$/, "");
  const hit = (Object.keys(TAB_ROUTES) as ControlTab[]).find((t) => TAB_ROUTES[t] === base);
  return hit ?? null;
}
